# Generated by Django 6.0.1 on 2026-01-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('study', '공부'), ('travel', '여행'), ('game', '게임')], default='free', max_length=20, verbose_name='카테고리'),
        ),
    ]
