# Generated by Django 6.0.1 on 2026-02-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글 목록'},
        ),
    ]
