# Generated by Django 6.0.1 on 2026-02-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_todolist_created_at_alter_todolist_modify_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='modify_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='modify_at',
            new_name='updated_at',
        ),
    ]
