# Generated by Django 6.0.1 on 2026-02-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_rename_content_comment_message_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='completed_image',
            field=models.ImageField(blank=True, null=True, upload_to='todo/%Y/%m/%d', verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='thumbnail',
            field=models.ImageField(blank=True, default='no_image/image.png', null=True, upload_to='todo/%Y/%m/%d/thumbnail', verbose_name='썸네일'),
        ),
    ]
